const nomboutique="Boutique vendeur";
const bienvenue= "salut bienvenue";

const privacityPolicy="les termes et politiques de confidentialité";
const bord="Tableau",
      tBord="Tableau de bord",
    commande="Commande",
    produits="Produits",
    parametre="Parametre",
    evalution="Evolution",
    venteTotal= "Vente total",
    produitPopulaire= "Produits publié",
    nonPaye="Non payer",
    paramettreBoutique="Paramettre de la boutique",
    messagerie="Messagerie",
    quitter="Quitter",
    editer="Editer",
    supprimer="Supprimer",
    vedette="Populaire",
    enregistrer="Enregistrer",
    editerProfile="Editer profile",
    nomBoutique="Nom boutique",
    password="Mot de passe",
    hintPassword="Entrer mot de passe",
    confirmer="Confirmer",
    hintConfirmer="Confirmer votre mot de passe",
    adresseBoutique="Adresse",
    numeroBoutique="Numero",
    description="Description",
    descriptionBoutique="Entrer la description de la boutique",
    message="Messages",
    connecter="Connecter",
    connexionreussi="Connexion avec succes",
    inscrie="Inscription";

const inscrireussie= "Votre inscription a été enrégistré avec succes";
const incrireIns="s'inscrire";
const vousAvez="vous avez deja un compte? ";
